
with open('maze_map.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x   x   xx xx        x\n')
  outfile.write('x     x     xxxxxxxxxx\n')
  outfile.write('x x    xx  xxxx xxx xx\n')
  outfile.write('  x   x x xx   xxxx  x\n')
  outfile.write('x          xx  xx  x x\n')
  outfile.write('xxxxxxx x      xx  x x\n')
  outfile.write('xxxxxxxxx  x x  xx   x\n')
  outfile.write('x          x x Sx x  x\n')
  outfile.write('xxxxx x  x x x     x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')


with open('maze_map1.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xx xxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x       xx xx        x\n')
  outfile.write('x                    x\n')
  outfile.write('xx              xxxxxx\n')
  outfile.write('x                    x\n')
  outfile.write('x  x          xxx  xxx\n')
  outfile.write('xxxxx              x x\n')
  outfile.write('xxxxxxxxx    xxxxx   x\n')
  outfile.write('x          xxx S     x\n')
  outfile.write('xxxxx x x          x x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')

with open('maze_map3.txt', 'w') as outfile:
  outfile.write('0\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx\n')
  outfile.write('x  x    x            x\n')
  outfile.write('x  x x      x x x    x\n')
  outfile.write('x    x  x   x   x    x\n')
  outfile.write('x    x  x   x   x    x\n')
  outfile.write('xx x    x       x    x\n')
  outfile.write('x       x   x   x    x\n')
  outfile.write('x xxxx  x   x   x    x\n')
  outfile.write('x  x x  xxxxx   x    x\n')
  outfile.write('xx   xxxx       x  S x\n')
  outfile.write('x  x        xxxxx    x\n')
  outfile.write('x  x  x  xxxx   x    x\n')
  outfile.write('x  x x  x       x    x\n')
  outfile.write('xx    x   x xxx x    x\n')
  outfile.write('x  x      x x   x    x\n')
  outfile.write('   xxxxxxxxxx xxx    x\n')
  outfile.write('x               x    x\n')
  outfile.write('xxxxxxxxxxxxxxxxxxxxxx')
